GOVERNMENT_ROLE_MANAGER = 'manager'
GOVERNMENT_ROLE_ADMIN = 'admin'

APARTMENT_ROLE_OWNER = 'owner'
APARTMENT_ROLE_TENANT = 'tenant'
APARTMENT_ROLE_LODGER = 'lodger'

APARTMENT_STATUS_UNDER_CONSIDERATION_GOVERNMENT = 'under consideration government'
APARTMENT_STATUS_UNDER_CONSIDERATION_HOUSE = 'under consideration house'
APARTMENT_STATUS_BLOCKED = 'blocked'
APARTMENT_STATUS_ACCEPTED = 'accepted'
